module.exports = [
  {
    captainName: "Picard",
    title: "Courage",
    post: "Courage can be an emotion too.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 100,
  },
  {
    captainName: "Ahab",
    title: "Whale",
    post: "By heavens man, we are turned round and round in this world, like yonder windlass, and fate is the handspike.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 20,
  },
  {
    captainName: "Sarah Lance",
    title: "Vandal Savage",
    post: "I’d tell you to go to hell, but you’d probably just feel at home there.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Ahab",
    title: "Insolence",
    post: "I don't give reasons. I give orders!",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 100,
  },
  {
    captainName: "Sarah Lance",
    title: "Ava",
    post: "Ava's the kind of girl that you take home to your parents, and I am the kind you take to an exorcism",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    captainName: "Ahab",
    title: "What is sleep?",
    post: "Sleep? That bed is a coffin, and those are winding sheets. I do not sleep, I die.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 5,
  },
  {
    captainName: "Sarah Lance",
    title: "Jonah Hex",
    post: "I know you don’t like taking orders from a woman, but you’re gonna like getting your ass kicked by one even less.",
    mistakesWereMadeToday: true,
    daysSinceLastCrisis: 0,
  },
  {
    date: 'April 1',
    taxes: 0.05,
    retirement: 10,
    save: 50,
    creditcard: 0.30,
    market: 50,
    internet: 110,
    pet: 20,
    car: 300,
    insurrance: 0,
    mistakesWereMadeToday: true,
    additional: 50,
},
{
    date: 'April 3',
    taxes: 0.05,
    retirement: 0,
    save: 0,
    creditcard: 0.30,
    market: 20,
    internet: 0,
    pet: 10,
    car: 50,
    insurrance: 0,
    mistakesWereMadeToday: true,
    additional: 15,
},
{
    date: 'April 5',
    taxes: 0.05,
    retirement: 0,
    save: 50,
    creditcard: 0.70,
    market: 40,
    internet: 0,
    pet: 10,
    car: 0,
    insurrance: 0,
    mistakesWereMadeToday: true,
    additional: 30,
},
{
    date: 'April 7',
    taxes: 0.05,
    retirement: 10,
    save: 0,
    creditcard: 0.50,
    market: 80,
    internet: 0,
    pet: 20,
    car: 0,
    insurrance: 0,
    mistakesWereMadeToday: true,
    additional: 90,
},
{
    date: 'April 13',
    taxes: 0.05,
    retirement: 0,
    save: 25,
    creditcard: 0.30,
    market: 20,
    internet: 0,
    pet: 0,
    car: 30,
    insurrance: 0,
    mistakesWereMadeToday: false,
    additional: 0,
},
{
  date: 'April 17',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  market: 10,
  internet: 0,
  pet: 30,
  car: 0,
  insurrance: 250,
  additional: 50,
},
{
  date: 'April 27',
  taxes: 0.05,
  retirement: 0,
  save: 10,
  creditcard: 0.30,
  market: 40,
  internet: 0,
  pet: 25,
  car: 0,
  insurrance: 0,
  additional: 150,
},
{
  date: 'May 1',
  taxes: 0.05,
  retirement: 10,
  save: 50,
  creditcard: 0.30,
  market: 50,
  internet: 110,
  pet: 20,
  car: 300,
  insurrance: 0,
  additional: 50,
  
},
{
  date: 'May 3',
  taxes: 0.05,
  save: 0,
  retirement: 0,
  creditcard: 0.30,
  market: 20,
  internet: 0,
  pet: 10,
  car: 50,
  insurrance: 0,
  additional: 15,
},
{
  date: 'May 5',
  taxes: 0.05,
  retirement: 0,
  save: 50,
  creditcard: 0.70,
  market: 40,
  internet: 0,
  pet: 10,
  car: 0,
  insurrance: 0,
  mistakesWereMadeToday: true,
  additional: 30,
},
{
  date: 'May 7',
  taxes: 0.05,
  retirement: 10,
  save: 0,
  creditcard: 0.50,
  market: 80,
  internet: 0,
  pet: 20,
  car: 0,
  insurrance: 0,
  additional: 90,
},
{
  date: 'May 13',
  taxes: 0.05,
  retirement: 0,
  save: 25,
  creditcard: 0.30,
  market: 20,
  internet: 0,
  pet: 0,
  car: 30,
  insurrance: 0,
  additional: 0,
},
{
  date: 'May 17',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  market: 10,
  internet: 0,
  pet: 30,
  car: 0,
  insurrance: 250,
  additional: 50,
},
{
  date: 'May 27',
  taxes: 0.05,
  retirement: 0,
  save: 10,
  creditcard: 0.30,
  market: 40,
  internet: 0,
  pet: 25,
  car: 0,
  insurrance: 0,
  mistakesWereMadeToday: true,
  additional: 85,
},
{
  date: 'Jun 1',
  taxes: 0.05,
  retirement: 10,
  save: 50,
  creditcard: 0.30,
  market: 50,
  internet: 110,
  pet: 20,
  car: 300,
  insurrance: 0,
  additional: 50,
},
{
  date: 'Jun 3',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  internet: 0,
  market: 20,
  pet: 10,
  car: 50,
  insurrance: 0,
  additional: 15,
},
{
  date: 'Jun 5',
  taxes: 0.05,
  retirement: 0,
  save: 50,
  creditcard: 0.70,
  market: 40,
  internet: 0,
  pet: 10,
  car: 0,
  insurrance: 0,
  additional: 30,
},
{
  date: 'Jun 7',
  taxes: 0.05,
  retirement: 10,
  save: 0,
  creditcard: 0.50,
  market: 80,
  internet: 0,
  pet: 20,
  car: 0,
  insurrance: 0,
  mistakesWereMadeToday: true,
  additional: 90,
},
{
  date: 'Jun 13',
  taxes: 0.05,
  retirement: 0,
  save: 25,
  creditcard: 0.30,
  market: 20,
  internet: 0,
  pet: 0,
  car: 30,
  insurrance: 0,
  additional: 0,
},
{
  date: 'Jun 17',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  market: 10,
  internet: 0,
  pet: 30,
  car: 0,
  insurrance: 250,
  additional: 50,
},
{
  date: 'Jun 27',
  taxes: 0.05,
  retirement: 0,
  save: 10,
  creditcard: 0.30,
  market: 40,
  internet: 0,
  pet: 25,
  car: 0,
  insurrance: 0,
  mistakesWereMadeToday: true,
  additional: 200,
},
{
  date: 'July 1',
  taxes: 0.05,
  retirement: 10,
  save: 50,
  creditcard: 0.30,
  market: 50,
  internet: 110,
  pet: 20,
  car: 300,
  insurrance: 0,
  additional: 50,
},
{
  date: 'July 3',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  internet: 0,
  market: 20,
  pet: 10,
  car: 50,
  insurrance: 0,
  additional: 15,
},
{
  date: 'July 5',
  taxes: 0.05,
  retirement: 0,
  save: 50,
  creditcard: 0.70,
  market: 40,
  internet: 0,
  pet: 10,
  car: 0,
  insurrance: 0,
  mistakesWereMadeToday: true,
  additional: 30,
},
{
  date: 'July 7',
  taxes: 0.05,
  retirement: 10,
  save: 0,
  creditcard: 0.50,
  market: 80,
  internet: 0,
  pet: 20,
  car: 0,
  insurrance: 0,
  additional: 90,
},
{
  date: 'July 13',
  taxes: 0.05,
  retirement: 0,
  save: 25,
  creditcard: 0.30,
  market: 20,
  internet: 0,
  pet: 0,
  car: 30,
  insurrance: 0,
  additional: 0,
},
{
  date: 'July 17',
  taxes: 0.05,
  retirement: 0,
  save: 0,
  creditcard: 0.30,
  market: 10,
  internet: 0,
  pet: 30,
  car: 0,
  insurrance: 250,
  additional: 50,

},
{
  date: 'July 27',
  taxes: 0.05,
  retirement: 0,
  save: 10,
  creditcard: 0.30,
  market: 40,
  internet: 0,
  pet: 25,
  car: 0,
  insurrance: 0,
  additional: 105,
},

];
